# Generated by Django 6.1.2 on 2026-10-09 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0002_normalize_authors_categories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='publication_year',
            new_name='ano_publicado',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='available',
            new_name='disponivel',
        ),
    ]
