# Generated by Django 6.1.2 on 2026-10-09 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("biblioteca", "0005_remove_legacy_author"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book",
            old_name="publication_year",
            new_name="data_publicacao",
        ),
        migrations.RenameField(
            model_name="book",
            old_name="available",
            new_name="disponivel",
        ),
    ]
